name: Enforcing pylint checks
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  update_python:
    runs-on: ubuntu-latest
    name: Updating python
    steps:
      - name: Install Python 3.7
        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
        id: install_python_3_7
      - name: Python version
        run: python -v
      - name: update pip
        run: python3 -m pip install --upgrade --no-cache-dir pip
        id: pip-install
      - name: fetch/update pylint
        run: python3 -m pip install --upgrade --no-cache-dir pylint
        id: pylint-install
  get_pylint_rc:
    runs-on: ubuntu-latest
    needs: update_python
    name: Fetch pylint.rc file
    steps:
      - run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
  run_pylint:
    runs-on: ubuntu-latest
    needs: get_pylint_rc
    name: Running pylint
    steps:
      - run: python3 -m pylint --rcfile ./pylint.rc **/*.py
